# Generated by Django 5.0.10 on 2025-01-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('cliente', 'Client'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
