# Generated by Django 5.0.10 on 2025-02-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorylog',
            name='type',
            field=models.CharField(choices=[('completa', 'Completa'), ('parcial', 'Parcial')], default='Parcial', max_length=50),
        ),
    ]
