# Generated by Django 5.1.4 on 2025-01-08 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs_App', '0002_auditorylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorylog',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Logs_App.connectionlog'),
            preserve_default=False,
        ),
    ]
