# Generated by Django 5.0.10 on 2025-06-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs_App', '0002_auditorylog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorylog',
            name='criticidad',
            field=models.FloatField(default=0),
        ),
    ]
