# Generated by Django 5.0.10 on 2025-01-22 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controls_Information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idx', models.IntegerField(default=0)),
                ('name', models.CharField(default='Control Name', max_length=255)),
                ('chapter', models.CharField(choices=[('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven')], default='2', max_length=10)),
                ('description', models.TextField(default='Description')),
                ('impact', models.TextField(default='Impact')),
                ('good_config', models.TextField(default='Este parámetro se encuentra configurado de forma correcta en su servidor.')),
                ('bad_config', models.TextField(default='Este parámetro se encuentra configurado de forma incorrecta en su servidor. Para remediar esta configuración ejecute el siguiente comando: ')),
                ('ref', models.URLField(default='http://References.ref')),
            ],
            options={
                'unique_together': {('idx', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='Controls_Scripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='automatic', max_length=10)),
                ('query_sql', models.TextField(blank=True, null=True)),
                ('control_script_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsideDB_App.controls_information')),
            ],
        ),
    ]
