# Generated by Django 5.1.4 on 2024-12-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsideDB_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controls_information',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
